### ISSUE TITLE
5000端口冲突

### ISSUE THREAD

**Issue by leadorzf** [Aquish-Lee/cookiecutter-pytorch-fastapi#1]
supervisor中同时启动gunicorn和fastapi，而两者都使用5000端口，会造成其中一个程序实际没有运行，supervisor中是否只需要gunicorn

**Comment by Aquish-Lee** [comment]
感谢提出，这里实际是一个遗留bug，最初保留main.py启动fastapi是为了在加入gunicorn前，单独对接口进行业务测试。

从gunicorn启动命令及配置文件也可以看出，实际gunicorn是对api.py中app对象进行多个进程pre-fork。

所以无需执行main.py，直接通过gunicorn实例化fastapi app对象，并将gunicorn主程序端口绑定至5000是正确的操作
